// 1. Load the secret API Key from environment variables
const GEMINI_API_KEY = process.env.GEMINI_API_KEY; 
// ...
// function callGeminiAPI(prompt) {
// ...
// const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
// ...
